import {readdir, writeFile} from 'fs/promises'
import {createServer} from 'livereload'
import express from 'express'
import {resolve} from 'path'

const basePath = '/git-blog',
      port = 3000,
      path = resolve(),
      posts = await readdir('posts/', {recursive: true}),
      postList = posts.map(p => `'${p}'`),
      serveStatic = express.static(path)

writeFile('posts.js',
          `// Generated by server.js\nexport default [${postList}]`)

express()
  .use(serveStatic)
  .use(basePath, serveStatic)
  .get('*', (_, res) => res.sendFile(resolve('index.html')))
  .listen(port, () => console.log(`Running at http://localhost:${port}`))

createServer({exts: ['css', 'js', 'md']}).watch(path)
