module.exports =
  [{devServer: {client: {overlay: {warnings: false},
                         progress: true},
                static: {directory: __dirname},
                open: true,
                watchFiles: ['index.html', 'src/**/*', 'public/**/*']},
    devtool: 'source-map',
    mode: 'production',
    // TODO: See if `module` defaults make this section unnecessary.
    module: {rules: [{test: /\.js$/,
                      use: [{loader: 'babel-loader',
                             options: {presets: [['@babel/preset-env',
                                                  {targets: 'defaults'}]]}}],
                      exclude: /node_modules/},
                     {test: /\.css$/,
                      use: [ 'style-loader', 'css-loader' ]},
                     {test: /\.png$/,
                      use: [{loader: 'url-loader',
                             options: {mimetype: 'image/png'}}]},
                     {test: /\.svg$/, use: 'file-loader'}]},
    output: {clean: true,
             publicPath: '/'}}]
